version: '2'
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    links:
      - app
  app:
    container_name: app
    restart: always
    build: .
    working_dir: /rest-framework-tutorial
    volumes:
      - .:/rest-framework-tutorial
    command: supervisord -n
    expose:
      - "8080"